[2022-02-12 23:27:58,115] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 23:27:58,154] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 23:27:58,154] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 23:27:58,155] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-12 23:27:58,155] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 23:27:58,210] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): accurate> on 2022-02-11 00:00:00+00:00
[2022-02-12 23:27:58,225] {standard_task_runner.py:52} INFO - Started process 376 to run task
[2022-02-12 23:27:58,230] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2022-02-11T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpwwulzr8k', '--error-file', '/tmp/tmp_szk9e64']
[2022-02-12 23:27:58,231] {standard_task_runner.py:77} INFO - Job 15: Subtask accurate
[2022-02-12 23:27:58,370] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2022-02-11T00:00:00+00:00 [running]> on host f9b316006a9e
[2022-02-12 23:27:58,527] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T00:00:00+00:00
[2022-02-12 23:27:58,530] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 23:27:58,532] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-02-12 23:27:58,562] {subprocess.py:85} INFO - Output:
[2022-02-12 23:27:58,578] {subprocess.py:89} INFO - accurate
[2022-02-12 23:27:58,579] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-12 23:27:58,646] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220211T000000, start_date=20220212T232758, end_date=20220212T232758
[2022-02-12 23:27:58,727] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-12 23:27:58,826] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
